"""empty message

Revision ID: 01f720f4d1e3
Revises: 6062b4a9943f
Create Date: 2023-01-08 18:19:13.763889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01f720f4d1e3'
down_revision = '6062b4a9943f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apartment', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apartment', 'description')
    # ### end Alembic commands ###
